// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SheetService.Data;

#nullable disable

namespace SheetService.Migrations
{
    [DbContext(typeof(SheetDbContext))]
    [Migration("20260307191334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SheetService.Models.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AC")
                        .HasColumnType("integer")
                        .HasColumnName("ac");

                    b.Property<int>("Cha")
                        .HasColumnType("integer")
                        .HasColumnName("cha");

                    b.Property<int>("Con")
                        .HasColumnType("integer")
                        .HasColumnName("con");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("Danger")
                        .HasColumnType("integer")
                        .HasColumnName("danger");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Dex")
                        .HasColumnType("integer")
                        .HasColumnName("dex");

                    b.Property<int>("Int")
                        .HasColumnType("integer")
                        .HasColumnName("int");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Str")
                        .HasColumnType("integer")
                        .HasColumnName("str");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Wis")
                        .HasColumnType("integer")
                        .HasColumnName("wis");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("idx_monsters_created_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_monsters_status");

                    b.ToTable("monsters", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
