// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SceneService.Data;

#nullable disable

namespace SceneService.Migrations
{
    [DbContext(typeof(SceneDbContext))]
    [Migration("20260325122440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SceneService.Models.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_username");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_players");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Reward")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reward");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("idx_scenes_created_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_scenes_status");

                    b.ToTable("scenes", (string)null);
                });

            modelBuilder.Entity("SceneService.Models.SceneMonster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AC")
                        .HasColumnType("integer")
                        .HasColumnName("ac");

                    b.Property<int>("Cha")
                        .HasColumnType("integer")
                        .HasColumnName("cha");

                    b.Property<int>("Con")
                        .HasColumnType("integer")
                        .HasColumnName("con");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_username");

                    b.Property<double>("Danger")
                        .HasColumnType("double precision")
                        .HasColumnName("danger");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Dex")
                        .HasColumnType("integer")
                        .HasColumnName("dex");

                    b.Property<int>("Int")
                        .HasColumnType("integer")
                        .HasColumnName("int");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<string>("MonsterId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.Property<int>("Str")
                        .HasColumnType("integer")
                        .HasColumnName("str");

                    b.Property<int>("Wis")
                        .HasColumnType("integer")
                        .HasColumnName("wis");

                    b.HasKey("Id");

                    b.HasIndex("SceneId")
                        .HasDatabaseName("idx_scene_monsters_scene_id");

                    b.ToTable("scene_monsters", (string)null);
                });

            modelBuilder.Entity("SceneService.Models.SceneMonster", b =>
                {
                    b.HasOne("SceneService.Models.Scene", "Scene")
                        .WithMany("Monsters")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("SceneService.Models.Scene", b =>
                {
                    b.Navigation("Monsters");
                });
#pragma warning restore 612, 618
        }
    }
}
